test:
  image: node:12
  stage: test
  script:
    - cd front
    - npm ci
    - npm run build
    - mv dist ../test
  artifacts:
    paths:
      - test
  except:
    - master

pages: # the job must be named pages
  image: node:12
  stage: deploy
  script:
    - cd front
    - npm ci
    - npm run build
    - mv dist ../public # rename the dist folder (result of npm run build)
  artifacts:
    paths:
      - public # artifact path must be /public for GitLab Pages to pick it up
  only:
    - master
