swagger: '2.0'
info:
  title: Lottery API
  version: '1.0'
host: localhost:8080
schemes:
  - http
paths:
  /prize_fund:
    get:
      tags:
        - API
      produces:
        - application/json
      responses:
        '200':
          description: 'Prize fund for the current round'
          schema:
            $ref: '#/definitions/PrizeFund'
  /participants:
    get:
      tags:
        - API
      produces:
        - application/json
      responses:
        '200':
          description: 'List of participants for the current round'
          schema:
            $ref: '#/definitions/Participants'
  /lucky_nums:
    get:
      tags:
        - API
      produces:
        - application/json
      responses:
        '200':
          description: 'Winning nums for the previous round'
          schema:
            $ref: '#/definitions/LuckyNums'
  /prizes:
    get:
      tags:
        - API
      produces:
        - application/json
      responses:
        '200':
          description: 'Prizes for the previous round'
          schema:
            $ref: '#/definitions/Prizes'
  /is_winner:
    get:
      tags:
        - API
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/addrParam'
      responses:
        '200':
          description: 'Prize for the addr for all previuos rounds'
          schema:
            $ref: '#/definitions/IsWinner'
definitions:
  PrizeFund:
    type: object
    properties:
      prize_fund:
        type: integer
        format: int64
  Participants:
    type: object
    properties:
      participants:
        type: array
        items:
          $ref: '#/definitions/Participant'
  Participant:
    type: object
    properties:
      addr:
        type: object
        properties:
          wc:
            type: integer
            format: int8
          addr:
            type: string
      nums:
        type: object
        properties:
          n1:
            type: integer
            format: uint8
          n2:
            type: integer
            format: uint8
          n3:
            type: integer
            format: uint8
  LuckyNums:
    type: object
    properties:
      lucky_nums:
        type: array
        items:
          type: integer
          format: uint8
  Prizes:
    type: object
    properties:
      p1:
        type: integer
        format: int64
      p2:
        type: integer
        format: int64
      p3:
        type: integer
        format: int64
  IsWinner:
    type: object
    properties:
      prize:
        type: integer
        format: int64
parameters:
  addrParam:
    name: addr
    in: query
    type: string
    required: true
